#!/usr/bin/env python3
"""B18 momentum-long losers study (2026-10-08) — read-only research. Headline: ML_B1H_NEGFLANK (DECISION_LOG 210).
Writes reports/ML_B18_STUDY_tables.md (raw tables) + reports/ML_B18_STUDY_sweep.csv. The narrative report is written by hand.
    venv/bin/python scripts/study_ml_b18_losers.py
"""
import itertools, sys, os
import numpy as np, pandas as pd
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__))))
import study_ml_b18_common as C

RNG = np.random.default_rng(11)
NSH = 1000
OUT = []


def say(s=""):
    OUT.append(s); print(s)


def fmt(st, ns=1):
    if st.get("N", 0) == 0:
        return "0"
    return (f"{st['N']:.0f} · {st['WR']:.0f}% · {st['avg']:+.3f}% · ${st['usd']:+,.0f} · {st['days']}d · "
            f"CI [{st['lo']:+.3f}, {st['hi']:+.3f}] · P(<0) {st['p_neg']:.2f}")


def row(label, d, ns=1):
    st = C.stats(d, ns)
    say(f"| {label} | {fmt(st)} |")
    return st


M = C.master()
M1 = C.master(include_b1=True)
Y = C.yr5()
NS = Y.seed.nunique()
for d in (M, M1, Y):
    d["slope"] = pd.to_numeric(d.entry_btc_1h_slope, errors="coerce")
    d["neg"] = d.slope <= -0.05
    d["b20"] = pd.to_numeric(d.entry_btc_ema20_slope, errors="coerce")
    d["gvol"] = pd.to_numeric(d.entry_global_volume_ratio, errors="coerce")
    d["brsi"] = pd.to_numeric(d.entry_btc_rsi, errors="coerce")
    d["tgap"] = pd.to_numeric(d.entry_btc_trend_gap_pct, errors="coerce")
    d["peak"] = pd.to_numeric(d.peak_pnl, errors="coerce"); d["trough"] = pd.to_numeric(d.trough_pnl, errors="coerce")
    d["half"] = np.where(d.o < d.o.quantile(0.5), "H1", "H2")

Y["usd"] = Y.usd  # per-fill $, stats divide by seeds where noted

say("# raw tables — B18 ML losers study (generated by scripts/study_ml_b18_losers.py)")
say(f"master kept ML ex-B1: {len(M)} fills · with B1: {len(M1)} · yr5 trimmed ML: {len(Y)} fills ({NS} seeds, {len(Y)/NS:.0f}/seed) "
    f"{Y.o.min():%Y-%m-%d}→{Y.o.max():%Y-%m-%d}")
say(f"sleeve breakeven WR: master ex-B1 {C.be_wr(M):.1f}% · master ex-washed {C.be_wr(M[~M.washed30]):.1f}% · yr5 {C.be_wr(Y):.1f}%")

# ── per-batch table
say("\n## 1. Per-batch (master, today's stack) and per-month (yr5) — every row\n")
say("| era | N · WR · avg % · Σ$ · days · day-CI · P(<0) |\n|---|---|")
for e in ["B1", "BASE"] + [f"B{i}" for i in range(2, 19)]:
    g = M1[M1.era == e]
    if len(g):
        row(e + (" (1× probe era — not headline)" if e == "B1" else ""), g)
row("**ALL ex-B1**", M); row("ex-B1 ex-BASE", M[M.era != "BASE"]); row("ex-B1 ex-washed (off30 ≤ −15)", M[~M.washed30])
row("ex-B1 ex-BASE ex-washed", M[(M.era != "BASE") & ~M.washed30])
say("\n| yr5 month | N/seed · WR · avg % · Σ$/seed · days · day-CI · P(<0) |\n|---|---|")
for mo, g in Y.groupby("era"):
    st = C.stats(g, NS); say(f"| {mo} | {fmt(st)} |")
st = C.stats(Y, NS); say(f"| **ALL** | {fmt(st)} |")
st = C.stats(Y[~Y.washed30], NS); say(f"| ex-washed (off30 ≤ −15) | {fmt(st)} |")

# ── NEGFLANK headline
COH = [("master ex-B1", M, 1), ("master ex-B1 ex-BASE", M[M.era != "BASE"], 1),
       ("master ex-B1 ex-washed(off30)", M[~M.washed30], 1), ("master ex-B1 ex-BASE ex-washed", M[(M.era != "BASE") & ~M.washed30], 1),
       ("master ex-B1 ex-washed(date Jun18–Jul2)", M[~M.wash], 1),
       ("yr5 all", Y, NS), ("yr5 ex-washed(off30)", Y[~Y.washed30], NS), ("yr5 ex-washed(date)", Y[~Y.wash], NS)]
say("\n## 2. ML_B1H_NEGFLANK (BTC 1h EMA20 slope ≤ −0.05) vs rest\n")
say("| cohort | NEGFLANK: N · WR · avg % · Σ$ · days · day-CI · P(<0) | rest | Δ avg | sleeve BE WR |\n|---|---|---|---|---|")
for lab, d, ns in COH:
    a, b = C.stats(d[d.neg], ns), C.stats(d[~d.neg], ns)
    say(f"| {lab} | {fmt(a)} | {fmt(b)} | {a['avg'] - b['avg']:+.3f} | {C.be_wr(d):.1f}% |")
say(f"| B18's 3 | {fmt(C.stats(M[M.b18], 1))} | | | |")

say("\n### 2a. dose-response (BTC 1h slope buckets) — pre-registered cut −0.05; −0.15 / −0.20 are POST-HOC\n")
BK = [(-9, -0.30, "≤ −0.30"), (-0.30, -0.15, "(−0.30, −0.15]"), (-0.15, -0.05, "(−0.15, −0.05]"),
      (-0.05, 0.05, "(−0.05, +0.05] dead-band*"), (0.05, 9, "> +0.05")]
say("| bucket | master ex-B1 | master ex-B1 ex-washed | yr5 all | yr5 ex-washed |\n|---|---|---|---|---|")
for lo, hi, lab in BK:
    cells = []
    for d, ns in [(M, 1), (M[~M.washed30], 1), (Y, NS), (Y[~Y.washed30], NS)]:
        g = d[(d.slope > lo) & (d.slope <= hi)]
        st = C.stats(g, ns)
        cells.append("0" if st["N"] == 0 else f"{st['N']:.0f}·{st['WR']:.0f}%·{st['avg']:+.3f}·{st['days']}d")
    say(f"| {lab} | " + " | ".join(cells) + " |")
say("*today the live dead-band blocks (−0.05, +0.025); fills there are pre-dead-band history or doors.")
for cut in (-0.15, -0.20):
    for lab, d, ns in [("master ex-B1 ex-washed", M[~M.washed30], 1), ("yr5 ex-washed", Y[~Y.washed30], NS)]:
        a, b = C.stats(d[d.slope <= cut], ns), C.stats(d[d.slope > cut], ns)
        say(f"- POST-HOC cut ≤ {cut}: {lab}: {fmt(a)} vs rest {b['avg']:+.3f}")


def dayblock_null(d, mask_fn, n=NSH, stat="diff"):
    """shuffled-DAY null: whole days' outcome blocks are permuted in time order and re-laid onto the fixed features."""
    d = d.sort_values(["day", "o"]).reset_index(drop=True)
    mask = mask_fn(d).values
    p = d.pct.values
    days = d.day.values
    ud, start = np.unique(days, return_index=True)
    blocks = [p[s:e] for s, e in zip(start, list(start[1:]) + [len(p)])]
    obs = p[mask].mean() - p[~mask].mean()
    out = np.empty(n)
    for i in range(n):
        q = np.concatenate([blocks[j] for j in RNG.permutation(len(blocks))])
        out[i] = q[mask].mean() - q[~mask].mean()
    return obs, (out <= obs).mean(), out


say("\n### 2b. stability\n")
for lab, d, ns in [("master ex-B1", M, 1), ("master ex-B1 ex-washed", M[~M.washed30], 1), ("yr5 all", Y, NS), ("yr5 ex-washed", Y[~Y.washed30], NS)]:
    obs, p, nul = dayblock_null(d, lambda x: x.neg)
    say(f"- shuffled-day null ({NSH}) {lab}: Δ(NEG − rest) {obs:+.3f} · one-sided p(null ≤ obs) {p:.3f} · null 5th pct {np.percentile(nul, 5):+.3f}")
    for h in ("H1", "H2"):
        g = d[d.half == h]
        a, b = g[g.neg].pct, g[~g.neg].pct
        say(f"  - {h} ({g.o.min():%m-%d}→{g.o.max():%m-%d}): NEG {len(a)/ns:.0f}·{(a>0).mean()*100:.0f}%·{a.mean():+.3f} vs rest {b.mean():+.3f} → Δ {a.mean()-b.mean():+.3f}")
say("\nyr5 per month (NEG vs rest, per-seed N):\n\n| month | NEG N · WR · avg | rest avg | Δ | LOMO Δ (month left out) |\n|---|---|---|---|---|")
for mo, g in Y.groupby("era"):
    a, b = g[g.neg].pct, g[~g.neg].pct
    lo = Y[Y.era != mo]
    lomo = lo[lo.neg].pct.mean() - lo[~lo.neg].pct.mean()
    say(f"| {mo} | {len(a)/NS:.0f}·{(a>0).mean()*100 if len(a) else 0:.0f}%·{a.mean() if len(a) else float('nan'):+.3f} | {b.mean():+.3f} | "
        f"{(a.mean()-b.mean()) if len(a) else float('nan'):+.3f} | {lomo:+.3f} |")
say("\nmaster per batch (NEG vs rest):\n\n| era | NEG N · WR · avg | rest N · avg | leave-era-out Δ |\n|---|---|---|---|")
for e, g in M.groupby("era", sort=False):
    a, b = g[g.neg].pct, g[~g.neg].pct
    lo = M[M.era != e]
    say(f"| {e} | {len(a)}·{(a>0).mean()*100 if len(a) else 0:.0f}%·{a.mean() if len(a) else float('nan'):+.3f} | {len(b)}·{b.mean() if len(b) else float('nan'):+.3f} | "
        f"{lo[lo.neg].pct.mean()-lo[~lo.neg].pct.mean():+.3f} |")

# per-pair / per-day concentration of the NEG loss
say("\n### 2c. NEGFLANK loss concentration (ex-washed)\n")
for lab, d in [("master", M[~M.washed30 & M.neg]), ("yr5", Y[~Y.washed30 & Y.neg])]:
    st = C.stats(d, NS if lab == "yr5" else 1)
    loss = d[d.pct < 0]
    tp = (-loss.groupby("pair").pct.sum()).sort_values(ascending=False).head(3)
    td = (-loss.groupby("day").pct.sum()).sort_values(ascending=False).head(3)
    say(f"- {lab}: max day share {st['maxday']:.0f}% · max pair share {st['maxpair']:.0f}% · top pairs {dict(tp.round(2))} · top days {dict(td.round(2))}")

# ── interactions
say("\n### 2d. interactions (cell = NEGFLANK ∧ X; Δ vs NEGFLANK ∧ ¬X; shuffled-day null on the cell-vs-rest-of-sleeve Δ)\n")
INTER = [("BTC 5m EMA20 slope > 0 (bounce inside 1h pullback)", lambda x: x.b20 > 0),
         ("global vol ratio < 0.6", lambda x: x.gvol < 0.6),
         ("BTC RSI ≥ 60", lambda x: x.brsi >= 60),
         ("regime HEALTHY_BULL", lambda x: x.entry_btc_regime == "HEALTHY_BULL"),
         ("regime STRONG_BULL", lambda x: x.entry_btc_regime == "STRONG_BULL"),
         ("washed-out (off30 ≤ −15)", lambda x: x.washed30),
         ("b20>0 ∧ gvol<0.6 (B18 shape)", lambda x: (x.b20 > 0) & (x.gvol < 0.6)),
         ("b20>0 ∧ gvol<0.6 ∧ RSI≥60 (B18 shape)", lambda x: (x.b20 > 0) & (x.gvol < 0.6) & (x.brsi >= 60))]
say("| X | cohort | NEG∧X | NEG∧¬X | rest of sleeve avg | day-null p (cell worse) | H1 Δ / H2 Δ (cell − rest) |\n|---|---|---|---|---|---|---|")
for lab, f in INTER:
    wl = "washed" in lab
    for cl, d, ns in [("master" if wl else "master ex-washed", M if wl else M[~M.washed30], 1),
                      ("yr5" if wl else "yr5 ex-washed", Y if wl else Y[~Y.washed30], NS)]:
        x = f(d).fillna(False).astype(bool)
        cell = d[d.neg & x]; oth = d[d.neg & ~x]; rest = d[~(d.neg & x)]
        if len(cell) == 0:
            say(f"| {lab} | {cl} | 0 | | | | |"); continue
        obs, p, _ = dayblock_null(d, lambda z, f=f: (z.neg & f(z).fillna(False).astype(bool)), n=500)
        hs = []
        for h in ("H1", "H2"):
            g = d[d.half == h]; xx = f(g).fillna(False).astype(bool)
            c, r = g[g.neg & xx].pct, g[~(g.neg & xx)].pct
            hs.append(f"{c.mean() - r.mean():+.3f}" if len(c) else "–")
        say(f"| {lab} | {cl} | {fmt(C.stats(cell, ns))} | {fmt(C.stats(oth, ns))} | {rest.pct.mean():+.3f} | {p:.3f} | {' / '.join(hs)} |")

# ── exits on NEGFLANK
say("\n### 2e. how NEGFLANK fills lost (exit anatomy; caps-for-losers check)\n")
say("| cohort | group | N | peak <0.10 (straight down) | peak 0.10–0.40 | peak ≥0.40 (armed then reversed) | median peak | winners with trough ≤ −0.50 |\n|---|---|---|---|---|---|---|---|")
for lab, d, ns in [("master ex-washed", M[~M.washed30], 1), ("yr5 ex-washed", Y[~Y.washed30], NS)]:
    for grp, g in [("NEG losers", d[d.neg & (d.pct <= 0)]), ("rest losers", d[~d.neg & (d.pct <= 0)])]:
        pk = g.peak
        w = d[(d.neg if grp.startswith("NEG") else ~d.neg) & (d.pct > 0)]
        say(f"| {lab} | {grp} | {len(g)/ns:.0f} | {(pk < 0.10).mean()*100:.0f}% | {((pk >= 0.10) & (pk < 0.40)).mean()*100:.0f}% | "
            f"{(pk >= 0.40).mean()*100:.0f}% | {pk.median():+.2f} | {(w.trough <= -0.50).mean()*100:.0f}% of {len(w)/ns:.0f} |")

# ── task-4 specific tests
say("\n## 3. Specific candidate signatures (block-cohort vs rest)\n")
SPEC = [("NEGFLANK", lambda x: x.neg),
        ("NEGFLANK ∧ gvol < 0.6", lambda x: x.neg & (x.gvol < 0.6)),
        ("NEGFLANK ∧ b20 > 0", lambda x: x.neg & (x.b20 > 0)),
        ("BTC 1d < 0", lambda x: x.btc1d < 0),
        ("bearish day (1d < 0 ∧ trend gap < 0)", lambda x: (x.btc1d < 0) & (x.tgap < 0)),
        ("NEGFLANK ∧ 1d < 0", lambda x: x.neg & (x.btc1d < 0)),
        ("cooldown < 30 min after ML stop (sequential)", lambda x: x.cooldown),
        ("cluster ≥ 2 ML in prior 120 min", lambda x: x.cluster2),
        ("NEG ∧ b20>0 ∧ gvol<0.6 ∧ 1d<0 (B18 full shape)", lambda x: x.neg & (x.b20 > 0) & (x.gvol < 0.6) & (x.btc1d < 0))]
for lab, d, ns in [("master ex-B1 ex-washed", M[~M.washed30], 1), ("yr5 ex-washed", Y[~Y.washed30], NS)]:
    t = np.nanpercentile(d.gvol, [33.3, 66.7])
    say(f"\n**{lab}** (gvol terciles {t[0]:.2f} / {t[1]:.2f}; BE WR {C.be_wr(d):.1f}%)\n")
    say("| signature | cohort: N · WR · avg % · Σ$ · days · day-CI · P(<0) | maxday / maxpair loss share | rest avg | day-null p |\n|---|---|---|---|---|")
    spec = SPEC + [(f"NEG ∧ gvol low tercile (< {t[0]:.2f})", lambda x, t=t: x.neg & (x.gvol < t[0])),
                   (f"NEG ∧ gvol mid tercile", lambda x, t=t: x.neg & (x.gvol >= t[0]) & (x.gvol < t[1])),
                   (f"NEG ∧ gvol high tercile (≥ {t[1]:.2f})", lambda x, t=t: x.neg & (x.gvol >= t[1]))]
    for sl, f in spec:
        x = f(d).fillna(False).astype(bool)
        st = C.stats(d[x], ns)
        if st["N"] == 0:
            say(f"| {sl} | 0 | | | |"); continue
        obs, p, _ = dayblock_null(d, lambda z, f=f: f(z).fillna(False).astype(bool), n=500)
        bar = (st["WR"] < C.be_wr(d)) and st["p_neg"] >= 0.95 and st["days"] >= 8 and st["N"] >= 15 and st["maxday"] < 50 and st["maxpair"] < 50
        say(f"| {sl} | {fmt(st)} | {st['maxday']:.0f}% / {st['maxpair']:.0f}% | {d[~x].pct.mean():+.3f} | {p:.3f} | {'**BAR PASS**' if bar else ''}")

# ── exhaustive sweep
say("\n## 4. Exhaustive stamped-column sweep (1D sign/median/terciles + all-pairs 2D median quadrants)\n")
EXC = {"entry_price", "entry_fee", "entry_slippage_pct", "entry_desired_notional", "entry_liquidity_cap_notional",
       "entry_bracket_cap_notional", "entry_bracket_max_leverage", "entry_pair_volume_24h_usd", "entry_mcap_usd", "entry_cmc_rank"}
num = []
for c in sorted(set(M.columns) & set(Y.columns)):
    if not c.startswith("entry_") or c in EXC:
        continue
    a, b = pd.to_numeric(M[c], errors="coerce"), pd.to_numeric(Y[c], errors="coerce")
    if a.notna().mean() >= 0.8 and b.notna().mean() >= 0.8 and b.nunique() > 3:
        num.append(c)
low_cov = [c for c in sorted(set(M.columns) & set(Y.columns)) if c.startswith("entry_") and c not in num and c not in EXC
           and pd.to_numeric(Y[c], errors="coerce").notna().mean() >= 0.8 and pd.to_numeric(Y[c], errors="coerce").nunique() > 3]
say(f"columns with ≥ 80 % coverage on BOTH cohorts: {len(num)} · yr5-only (master coverage < 80 %, NOT swept on master): {low_cov}")
for c in num:
    M[c] = pd.to_numeric(M[c], errors="coerce"); Y[c] = pd.to_numeric(Y[c], errors="coerce")
Ye = Y[~Y.washed30].sort_values(["day", "o"]).reset_index(drop=True)
Me = M[~M.washed30].reset_index(drop=True)
masks = {}
for c in num:
    v = Ye[c]; med, t1, t2 = v.median(), v.quantile(1 / 3), v.quantile(2 / 3)
    if (v > 0).any() and (v <= 0).any():
        masks[(c, "≤0")] = (lambda s: s <= 0); masks[(c, ">0")] = (lambda s: s > 0)
    masks[(c, f"≤med {med:.3g}")] = (lambda s, m_=med: s <= m_); masks[(c, f">med {med:.3g}")] = (lambda s, m_=med: s > m_)
    masks[(c, f"≤T1 {t1:.3g}")] = (lambda s, m_=t1: s <= m_); masks[(c, f">T2 {t2:.3g}")] = (lambda s, m_=t2: s > m_)
oneD = list(masks.items())
twoD = []
for c1, c2 in itertools.combinations(num, 2):
    m1, m2 = Ye[c1].median(), Ye[c2].median()
    for s1, s2 in itertools.product([0, 1], [0, 1]):
        twoD.append(((c1 + ("≤" if s1 == 0 else ">") + f"{m1:.3g}", c2 + ("≤" if s2 == 0 else ">") + f"{m2:.3g}"),
                     (c1, m1, s1, c2, m2, s2)))


def mk(d, spec):
    c1, m1, s1, c2, m2, s2 = spec
    a = d[c1] <= m1 if s1 == 0 else d[c1] > m1
    b = d[c2] <= m2 if s2 == 0 else d[c2] > m2
    return (a & b & d[c1].notna() & d[c2].notna()).values


def mk1(d, key):
    c, _ = key
    return (masks[key](d[c]) & d[c].notna()).values


rows = [("1D", k[0] + " " + k[1], mk1(Ye, k), mk1(Me, k), k) for k, _ in oneD] + \
       [("2D", k[0] + " ∧ " + k[1], mk(Ye, s), mk(Me, s), s) for k, s in twoD]
MIN = 30 * NS // 3 * 3  # ≥ 30 fills (≈10/seed) in zone and outside
B = np.array([r[2] for r in rows], dtype=np.float32)
keep = (B.sum(1) >= 90) & ((1 - B).sum(1) >= 90)
B = B[keep]; rows = [r for r, k in zip(rows, keep) if k]
p = Ye.pct.values.astype(np.float32)


def zmat(B, P):
    n1 = B.sum(1, keepdims=True); n0 = B.shape[1] - n1
    s1 = B @ P; q1 = B @ (P ** 2); s = P.sum(0, keepdims=True); q = (P ** 2).sum(0, keepdims=True)
    m1 = s1 / n1; m0 = (s - s1) / n0
    v1 = q1 / n1 - m1 ** 2; v0 = (q - q1) / n0 - m0 ** 2
    return (m1 - m0) / np.sqrt(v1 / n1 + v0 / n0)


z = zmat(B, p[:, None])[:, 0]
# shuffled-DAY null on the max |z| (family-wise): permute whole-day outcome blocks
days = Ye.day.values; ud, st_ = np.unique(days, return_index=True)
blocks = [p[s:e] for s, e in zip(st_, list(st_[1:]) + [len(p)])]
NP = np.stack([np.concatenate([blocks[j] for j in RNG.permutation(len(blocks))]) for _ in range(NSH)], 1).astype(np.float32)
nullmax = np.nanmax(np.abs(zmat(B, NP)), 0)
NT = np.stack([RNG.permutation(p) for _ in range(NSH)], 1).astype(np.float32)
nullmax_t = np.nanmax(np.abs(zmat(B, NT)), 0)
zc_day, zc_tr = np.percentile(nullmax, 95), np.percentile(nullmax_t, 95)
say(f"tests: {len(rows)} masks (1D {sum(r[0]=='1D' for r in rows)} · 2D {sum(r[0]=='2D' for r in rows)}) on yr5 ex-washed ({len(Ye)} fills, {Ye.day.nunique()} days); "
    f"observed max |z| {np.nanmax(np.abs(z)):.2f} · family-wise 95th pct of the null max |z|: shuffled-DAY {zc_day:.2f} · shuffled-trade {zc_tr:.2f} · "
    f"P(null max ≥ observed max) day {np.mean(nullmax >= np.nanmax(np.abs(z))):.3f} / trade {np.mean(nullmax_t >= np.nanmax(np.abs(z))):.3f}")
recs = []
h1 = (Ye.half == "H1").values
mh1 = (Me.half == "H1").values
mp = Me.pct.values
months = Ye.era.values
for i, (k, lab, ym, mm, spec) in enumerate(rows):
    def d_(mask, pv, sel):
        a, b = pv[mask & sel], pv[~mask & sel]
        return (a.mean() - b.mean()) if len(a) >= 3 and len(b) >= 3 else np.nan
    allsel = np.ones(len(p), bool)
    dh1, dh2 = d_(ym, p, h1), d_(ym, p, ~h1)
    mons = [d_(ym, p, months == mo) for mo in np.unique(months)]
    lomo = [d_(ym, p, months != mo) for mo in np.unique(months)]
    mz = mm.astype(bool)
    recs.append(dict(kind=k, mask=lab, yr5_n=int(ym.sum()) / NS, yr5_avg=p[ym].mean(), yr5_rest=p[~ym].mean(), yr5_z=z[i],
                     yr5_H1=dh1, yr5_H2=dh2, months_same_sign=int(np.nansum(np.sign(mons) == np.sign(z[i]))), months_n=int(np.sum(~np.isnan(mons))),
                     lomo_min_abs_same=min([abs(x) if np.sign(x) == np.sign(z[i]) else -abs(x) for x in lomo if not np.isnan(x)] or [np.nan]),
                     yr5_days=int(Ye.day[ym].nunique()),
                     master_n=int(mz.sum()), master_avg=mp[mz].mean() if mz.any() else np.nan, master_rest=mp[~mz].mean() if (~mz).any() else np.nan,
                     master_days=int(Me.day[mz].nunique()),
                     master_H1=d_(mz, mp, mh1), master_H2=d_(mz, mp, ~mh1)))
R = pd.DataFrame(recs)
R["master_delta"] = R.master_avg - R.master_rest
R["fw_day_pass"] = R.yr5_z.abs() > zc_day
R["oos_pass"] = (np.sign(R.yr5_H1) == np.sign(R.yr5_z)) & (np.sign(R.yr5_H2) == np.sign(R.yr5_z)) & (R.lomo_min_abs_same > 0)
R["master_agree"] = (np.sign(R.master_delta) == np.sign(R.yr5_z)) & (R.master_n >= 8)
R["all_pass"] = R.fw_day_pass & R.oos_pass & R.master_agree
R = R.reindex(R.yr5_z.abs().sort_values(ascending=False).index)
R.to_csv("reports/ML_B18_STUDY_sweep.csv", index=False)
say(f"survivors: family-wise (day null) {int(R.fw_day_pass.sum())} · + both halves & LOMO {int((R.fw_day_pass & R.oos_pass).sum())} · "
    f"+ master direction (N ≥ 8) {int(R.all_pass.sum())}")
say("\nTop 20 by |z| (yr5 ex-washed):\n\n| kind | mask | yr5 N/seed · zone avg · rest · z | H1Δ / H2Δ | months same sign | LOMO min | master N · avg · Δ · days | master H1Δ / H2Δ | pass |\n|---|---|---|---|---|---|---|---|---|")
for _, r in R.head(20).iterrows():
    say(f"| {r.kind} | {r['mask']} | {r.yr5_n:.0f} · {r.yr5_avg:+.3f} · {r.yr5_rest:+.3f} · {r.yr5_z:+.2f} | {r.yr5_H1:+.3f} / {r.yr5_H2:+.3f} | "
        f"{r.months_same_sign}/{r.months_n} | {r.lomo_min_abs_same:+.3f} | {r.master_n} · {r.master_avg:+.3f} · {r.master_delta:+.3f} · {r.master_days}d | "
        f"{r.master_H1:+.3f} / {r.master_H2:+.3f} | {'FW' if r.fw_day_pass else ''}{' OOS' if r.oos_pass else ''}{' M' if r.master_agree else ''} |")
neg_rows = R[R['mask'].str.contains("entry_btc_1h_slope")]
say("\nBTC 1h slope rows in the sweep (where NEGFLANK-like masks land in the family):\n")
for _, r in neg_rows.head(8).iterrows():
    say(f"- {r['mask']}: z {r.yr5_z:+.2f} (FW cut {zc_day:.2f}) · master Δ {r.master_delta:+.3f} (N {r.master_n})")

open("reports/ML_B18_STUDY_tables.md", "w").write("\n".join(OUT) + "\n")
print("wrote reports/ML_B18_STUDY_tables.md, reports/ML_B18_STUDY_sweep.csv")
